version: '3'
    
services:
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - db-volume:/var/lib/postgres
  #   networks:
  #     - app-network

  app:
    build: .
    # command: nginx
    image: sendfile
    restart: unless-stopped
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    # working_dir: /code
    networks:
      - app-network

# volumes:
#   db-volume: 

networks:
  app-network:
    driver: bridge

