# Generated by Django 3.1.1 on 2020-09-15 04:34

from django.db import migrations, models
import threadwatcher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inputfile', models.FileField(upload_to=threadwatcher.models.file_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
