# Generated by Django 3.1.1 on 2020-09-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadwatcher', '0002_bthread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bthread',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
